### ISSUE TITLE
roadmap, todo list

### ISSUE THREAD

**Issue by ayame113** [ayame113/atom-ide-deno#2]
この拡張機能で実装を検討している機能のリスト

 - [ ] 設定画面からのパッケージの有効化/無効化（node.js拡張との共存）
 - [ ] ファイル名に基づいたパッケージの有効化/無効化（node.js拡張との共存）
 - [ ] 保存時にコードをフォーマットする。設定画面からのその機能の有効化/無効化
 - [ ] コマンドのGUI操作
 - [ ] カスタムリクエスト（https://github.com/denoland/deno/tree/main/cli/lsp に記載されているもの）
 - [ ] vscode拡張で利用できる何か

これらの実装作業は現在行われていません…。
コメントでリクエストがあれば、実装作業を開始したいと思います。

**Comment by ayame113** [comment]
According to the atom-ide package roadmap (https://github.com/atom-community/website/issues/3#issue-424527067), code formatting will be implemented in the future.

Overall, you need to triage what implement on the deno side and what implement on the atom-ide side.
